### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by Meta404Dev** [CodeGize/UnitySapi#1]
![image](https://cloud.githubusercontent.com/assets/20500026/25367827/f2b66228-29aa-11e7-9a2b-31c932c0a66a.png)

点击Connect后显示上图，再点其他按钮无反应

**Comment by CodeGize** [comment]
![image](https://cloud.githubusercontent.com/assets/9925061/25369326/993f6f2c-29b5-11e7-80e2-1ad47f1dbc82.png)
点击Connect后点击InitServer，再点击Speak的演示结果
